// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enltzancrbqzkalynltc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubHR6YW5jcmJxemthbHlubHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4ODc5NTIsImV4cCI6MjA1MzQ2Mzk1Mn0.CfC8i1FTNV1Ac0fpJScfAHWiYfcrp8DCCWz5MUT35HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);